version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
      - storage:/app/storage
    depends_on:
      - mongo
    container_name: web-app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: mongo-db

volumes:
  mongo-data:
  storage:
